// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "检查服务是否正常运行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务状态",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/optimize": {
            "post": {
                "description": "使用修复版本的优化器进行营养配餐优化",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "优化算法"
                ],
                "summary": "正常优化（修复版本）",
                "parameters": [
                    {
                        "description": "优化请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.OptimizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "优化结果",
                        "schema": {
                            "$ref": "#/definitions/main.OptimizationResult"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/optimize-with-bugs": {
            "post": {
                "description": "使用含Bug版本的优化器进行测试，用于复现特定类型的科学计算Bug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "优化算法"
                ],
                "summary": "含Bug优化（测试版本）",
                "parameters": [
                    {
                        "enum": [
                            "precision_loss",
                            "numerical_overflow",
                            "constraint_violation",
                            "convergence_failure",
                            "result_instability"
                        ],
                        "type": "string",
                        "description": "Bug类型",
                        "name": "bug_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "优化请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.OptimizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "优化结果（含Bug信息）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Constraint": {
            "type": "object",
            "properties": {
                "ingredient_id": {
                    "type": "integer",
                    "example": 1
                },
                "type": {
                    "type": "string",
                    "example": "ingredient_min"
                },
                "value": {
                    "type": "number",
                    "example": 50
                }
            }
        },
        "main.Ingredient": {
            "type": "object",
            "properties": {
                "calcium": {
                    "type": "number",
                    "example": 11
                },
                "carbs": {
                    "type": "number",
                    "example": 0
                },
                "energy": {
                    "type": "number",
                    "example": 165
                },
                "fat": {
                    "type": "number",
                    "example": 3.6
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "iron": {
                    "type": "number",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "鸡胸肉"
                },
                "price": {
                    "type": "number",
                    "example": 0.8
                },
                "protein": {
                    "type": "number",
                    "example": 31
                },
                "vitamin_c": {
                    "type": "number",
                    "example": 0
                },
                "zinc": {
                    "type": "number",
                    "example": 0.7
                }
            }
        },
        "main.IngredientAmount": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 150.5
                },
                "calcium": {
                    "type": "number",
                    "example": 11
                },
                "carbs": {
                    "type": "number",
                    "example": 0
                },
                "energy": {
                    "type": "number",
                    "example": 165
                },
                "fat": {
                    "type": "number",
                    "example": 3.6
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "iron": {
                    "type": "number",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "鸡胸肉"
                },
                "price": {
                    "type": "number",
                    "example": 0.8
                },
                "protein": {
                    "type": "number",
                    "example": 31
                },
                "vitamin_c": {
                    "type": "number",
                    "example": 0
                },
                "zinc": {
                    "type": "number",
                    "example": 0.7
                }
            }
        },
        "main.NutritionGoal": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "number",
                    "example": 700
                },
                "min": {
                    "type": "number",
                    "example": 500
                },
                "nutrient": {
                    "type": "string",
                    "example": "energy"
                },
                "target": {
                    "type": "number",
                    "example": 600
                },
                "weight": {
                    "type": "number",
                    "example": 0.3
                }
            }
        },
        "main.NutritionSummary": {
            "type": "object",
            "properties": {
                "calcium": {
                    "type": "number",
                    "example": 300.5
                },
                "carbs": {
                    "type": "number",
                    "example": 80.3
                },
                "energy": {
                    "type": "number",
                    "example": 600.5
                },
                "fat": {
                    "type": "number",
                    "example": 15.8
                },
                "iron": {
                    "type": "number",
                    "example": 8.2
                },
                "protein": {
                    "type": "number",
                    "example": 30.2
                },
                "vitamin_c": {
                    "type": "number",
                    "example": 45.6
                },
                "zinc": {
                    "type": "number",
                    "example": 5.1
                }
            }
        },
        "main.OptimizationRequest": {
            "type": "object",
            "properties": {
                "constraints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Constraint"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Ingredient"
                    }
                },
                "max_iterations": {
                    "type": "integer"
                },
                "nutrition_goals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.NutritionGoal"
                    }
                },
                "tolerance": {
                    "type": "number"
                },
                "weights": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Weight"
                    }
                }
            }
        },
        "main.OptimizationResult": {
            "type": "object",
            "properties": {
                "converged": {
                    "type": "boolean",
                    "example": true
                },
                "cost": {
                    "type": "number",
                    "example": 15.5
                },
                "error": {
                    "type": "string"
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.IngredientAmount"
                    }
                },
                "iterations": {
                    "type": "integer",
                    "example": 50
                },
                "nutrition": {
                    "$ref": "#/definitions/main.NutritionSummary"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.Weight": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "example": "nutrition"
                },
                "value": {
                    "type": "number",
                    "example": 0.6
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "营养配餐多目标优化算法API",
	Description:      "营养配餐多目标优化算法测试套件，包含5类典型科学计算Bug的复现机制",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}